/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './_progress-bar.scss.shim.ngstyle';
import * as import1 from './_tag.scss.shim.ngstyle';
export const styles:any[] = [
  '',
  import0.styles,
  import1.styles
]
;
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvcmUvc3R5bGVzL2NvbXBvbmVudHMvX2NvbXBvbmVudHMuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9leWFsaGFraW0vZGV2L3JlcG9zL25nMi10YWctaW5wdXQvbW9kdWxlcy9jb21wb25lbnRzL3RhZy1pbnB1dC90YWctaW5wdXQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OzsifQ==
