/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['.progress-bar[_ngcontent-%COMP%], .progress-bar[_ngcontent-%COMP%]:before {\n    height: 2px;\n    width: 100%;\n    margin: 0;\n}\n\n.progress-bar[_ngcontent-%COMP%] {\n    background-color: map_get($color-focused, \'default\');\n    display: flex;\n    position: absolute;\n    bottom: 0;\n}\n\n.progress-bar[_ngcontent-%COMP%]:before {\n    background-color: lighten(map_get($color-focused, \'default\'), 20%);\n    content: \'\';\n    -webkit-animation: running-progress 2s cubic-bezier(0.4, 0, 0.2, 1) infinite;\n    animation: running-progress 2s cubic-bezier(0.4, 0, 0.2, 1) infinite;\n}\n\n@-webkit-keyframes running-progress {\n    0% { margin-left: 0; margin-right: 100%; }\n    50% { margin-left: 25%; margin-right: 0; }\n    100% { margin-left: 100%; margin-right: 0; }\n}\n\n@keyframes running-progress {\n    0% { margin-left: 0; margin-right: 100%; }\n    50% { margin-left: 25%; margin-right: 0; }\n    100% { margin-left: 100%; margin-right: 0; }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvcmUvc3R5bGVzL2NvbXBvbmVudHMvX3Byb2dyZXNzLWJhci5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvdGFnLWlucHV0L3RhZy1pbnB1dC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
