/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['tag[_ngcontent-%COMP%] {\n    @include tag-theme($default-tag-theme);\n}\n\n.minimal[_ngcontent-%COMP%]   tag[_ngcontent-%COMP%] {\n    @include tag-theme($minimal-tag-theme);\n}\n\n.dark[_ngcontent-%COMP%]   tag[_ngcontent-%COMP%] {\n    @include tag-theme($dark-tag-theme);\n}\n\n.bootstrap[_ngcontent-%COMP%]   tag[_ngcontent-%COMP%] {\n    @include tag-theme($bootstrap-tag-theme);\n}\n\n.bootstrap3-info[_ngcontent-%COMP%]   tag[_ngcontent-%COMP%] {\n    @include tag-theme($bootstrap3-info-tag-theme);\n\n    padding: .25em .6em;\n\n    text-align: center;\n    white-space: nowrap;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvcmUvc3R5bGVzL2NvbXBvbmVudHMvX3RhZy5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvdGFnLWlucHV0L3RhZy1pbnB1dC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
