/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['$dark-theme[_ngcontent-%COMP%]:   ([_ngcontent-%COMP%]   container-border-bottom[_ngcontent-%COMP%]:   2px[_ngcontent-%COMP%]   solid[_ngcontent-%COMP%]   map-get($color-primary[_ngcontent-%COMP%], \'dark\')\n)[_ngcontent-%COMP%];\n\n$dark-tag-theme[_ngcontent-%COMP%]:   ([_ngcontent-%COMP%]   background[_ngcontent-%COMP%]:   map-get($color-primary[_ngcontent-%COMP%], \'dark\')[_ngcontent-%COMP%], color[_ngcontent-%COMP%]:   #f9f9f9[_ngcontent-%COMP%], background-focused[_ngcontent-%COMP%]:   map-get($color-focused[_ngcontent-%COMP%], \'dark\')[_ngcontent-%COMP%], background-hover[_ngcontent-%COMP%]:   darken(map-get($color-primary[_ngcontent-%COMP%], \'dark\')[_ngcontent-%COMP%], 10%)[_ngcontent-%COMP%], color-focused[_ngcontent-%COMP%]:   map-get($color-primary[_ngcontent-%COMP%], \'dark\')[_ngcontent-%COMP%], color-hover[_ngcontent-%COMP%]:   #f9f9f9[_ngcontent-%COMP%], border-radius[_ngcontent-%COMP%]:   3px\n)[_ngcontent-%COMP%];\n\n$dark-icon-theme[_ngcontent-%COMP%]:   ([_ngcontent-%COMP%]   fill[_ngcontent-%COMP%]:   map-get($color-arrow[_ngcontent-%COMP%], \'dark\')[_ngcontent-%COMP%], fill-focus[_ngcontent-%COMP%]:   map-get($color-arrow-focused[_ngcontent-%COMP%], \'dark\')\n)[_ngcontent-%COMP%];\n\n.dark[_ngcontent-%COMP%]   tag[_ngcontent-%COMP%]:focus {\n    box-shadow: 0 0 0 1px #323232;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvcmUvc3R5bGVzL3RoZW1lcy9fZGFyay10aGVtZS5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvdGFnLWlucHV0L3RhZy1pbnB1dC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
