/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['$minimal-theme[_ngcontent-%COMP%]:   ([_ngcontent-%COMP%]   container-border-bottom[_ngcontent-%COMP%]:   1px[_ngcontent-%COMP%]   solid[_ngcontent-%COMP%]   transparent\n)[_ngcontent-%COMP%];\n\n$minimal-tag-theme[_ngcontent-%COMP%]:   ([_ngcontent-%COMP%]   background[_ngcontent-%COMP%]:   map-get($color-primary[_ngcontent-%COMP%], \'minimal\')[_ngcontent-%COMP%], background-hover[_ngcontent-%COMP%]:   darken(map-get($color-primary[_ngcontent-%COMP%], \'minimal\')[_ngcontent-%COMP%], 5%)[_ngcontent-%COMP%], background-focused[_ngcontent-%COMP%]:   map-get($color-focused[_ngcontent-%COMP%], \'minimal\')[_ngcontent-%COMP%], background-active[_ngcontent-%COMP%]:   map-get($color-focused[_ngcontent-%COMP%], \'minimal\')[_ngcontent-%COMP%], border-radius[_ngcontent-%COMP%]:   0[_ngcontent-%COMP%], color-active[_ngcontent-%COMP%]:   initial[_ngcontent-%COMP%], color-focused[_ngcontent-%COMP%]:   initial\n)[_ngcontent-%COMP%];\n\n$minimal-icon-theme[_ngcontent-%COMP%]:   ([_ngcontent-%COMP%]   fill[_ngcontent-%COMP%]:   map-get($color-arrow[_ngcontent-%COMP%], \'minimal\')[_ngcontent-%COMP%], fill-focus[_ngcontent-%COMP%]:   map-get($color-arrow-focused[_ngcontent-%COMP%], \'minimal\')\n)[_ngcontent-%COMP%];'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvcmUvc3R5bGVzL3RoZW1lcy9fbWluaW1hbC10aGVtZS5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvdGFnLWlucHV0L3RhZy1pbnB1dC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
