/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '../core/_core.scss.shim.ngstyle';
import * as import1 from './_default-theme.scss.shim.ngstyle';
import * as import2 from './_minimal-theme.scss.shim.ngstyle';
import * as import3 from './_dark-theme.scss.shim.ngstyle';
import * as import4 from './_bootstrap-theme.scss.shim.ngstyle';
import * as import5 from './_bootstrap3-info-theme.scss.shim.ngstyle';
export const styles:any[] = [
  '//[_ngcontent-%COMP%]   THEMES\n\n\n\n\n\n\n\n\n.ng2-tag-input[_ngcontent-%COMP%] {\n    @include tag-input-theme($default-theme);\n}\n\n.minimal.ng2-tag-input[_ngcontent-%COMP%] {\n    @include tag-input-theme($minimal-theme);\n}\n\n.dark.ng2-tag-input[_ngcontent-%COMP%] {\n    @include tag-input-theme($dark-theme);\n}\n\n.bootstrap.ng2-tag-input[_ngcontent-%COMP%] {\n    @include tag-input-theme($bootstrap-theme);\n}\n\n.bootstrap3-info.ng2-tag-input[_ngcontent-%COMP%] {\n    @include tag-input-theme($bootstrap3-info-theme);\n}\n\n.error-message[_ngcontent-%COMP%] {\n    @include error-message($default-theme);\n}\n\n.bootstrap[_ngcontent-%COMP%]   .error-message[_ngcontent-%COMP%] {\n    @include error-message($bootstrap-theme);\n}',
  import0.styles,
  import1.styles,
  import2.styles,
  import3.styles,
  import4.styles,
  import5.styles
]
;
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvcmUvc3R5bGVzL3RoZW1lcy9fdGhlbWVzLnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXlhbGhha2ltL2Rldi9yZXBvcy9uZzItdGFnLWlucHV0L21vZHVsZXMvY29tcG9uZW50cy90YWctaW5wdXQvdGFnLWlucHV0LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
