/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '../../core/styles/themes/_themes.scss.shim.ngstyle';
export const styles:any[] = [
  'delete-icon[_nghost-%COMP%] {\n    @include icon-theme($default-icon-theme);\n}\n\ndelete-icon[_nghost-%COMP%]:hover {\n    transform: scale(1.5) translateY(-3px);\n}\n\n.dark[_nghost-%COMP%], .dark   [_nghost-%COMP%] {\n    @include icon-theme($dark-icon-theme);\n}\n\n.minimal[_nghost-%COMP%], .minimal   [_nghost-%COMP%] {\n    @include icon-theme($minimal-icon-theme);\n}\n\n.bootstrap[_nghost-%COMP%], .bootstrap   [_nghost-%COMP%] {\n    @include icon-theme($bootstrap-icon-theme);\n}\n\ntag[_nghost-%COMP%]:focus, tag:focus   [_nghost-%COMP%], tag[_nghost-%COMP%]:active, tag:active   [_nghost-%COMP%] {\n    @include icon-theme-focused($default-icon-theme);\n}\n\n.dark[_nghost-%COMP%]   tag[_ngcontent-%COMP%]:focus, .dark   tag:focus   [_nghost-%COMP%], .dark[_nghost-%COMP%]   tag[_ngcontent-%COMP%]:active, .dark   tag:active   [_nghost-%COMP%] {\n    @include icon-theme-focused($dark-icon-theme);\n}\n\n.minimal[_nghost-%COMP%]   tag[_ngcontent-%COMP%]:focus, .minimal   tag:focus   [_nghost-%COMP%], .minimal[_nghost-%COMP%]   tag[_ngcontent-%COMP%]:active, .minimal   tag:active   [_nghost-%COMP%] {\n    @include icon-theme-focused($minimal-icon-theme);\n}\n\n.bootstrap[_nghost-%COMP%]   tag[_ngcontent-%COMP%]:focus, .bootstrap   tag:focus   [_nghost-%COMP%], .bootstrap[_nghost-%COMP%]   tag[_ngcontent-%COMP%]:active, .bootstrap   tag:active   [_nghost-%COMP%] {\n    @include icon-theme-focused($bootstrap-icon-theme);\n}\n\n.bootstrap3-info[_nghost-%COMP%], .bootstrap3-info   [_nghost-%COMP%] {\n    @include icon-theme-focused($bootstrap3-info-icon-theme);\n    height: inherit;\n}',
  import0.styles
]
;
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvaWNvbi9pY29uLnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXlhbGhha2ltL2Rldi9yZXBvcy9uZzItdGFnLWlucHV0L21vZHVsZXMvY29tcG9uZW50cy9pY29uL2ljb24udHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7In0=
