/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './icon.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../modules/components/icon/icon';
const styles_DeleteIconComponent:any[] = [import0.styles];
export const RenderType_DeleteIconComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_DeleteIconComponent,
  data: {}
}
);
export function View_DeleteIconComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),6,'span',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),3,':svg:svg',[
      [
        'height',
        '16px'
      ]
      ,
      [
        'viewBox',
        '0 0 32 32'
      ]
      ,
      [
        'width',
        '16px'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n        '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),0,':svg:path',[
      [
        'd',
        'M17.459,16.014l8.239-8.194c0.395-0.391,0.395-1.024,0-1.414c-0.394-0.391-1.034-0.391-1.428,0  l-8.232,8.187L7.73,6.284c-0.394-0.395-1.034-0.395-1.428,0c-0.394,0.396-0.394,1.037,0,1.432l8.302,8.303l-8.332,8.286  c-0.394,0.391-0.394,1.024,0,1.414c0.394,0.391,1.034,0.391,1.428,0l8.325-8.279l8.275,8.276c0.394,0.395,1.034,0.395,1.428,0  c0.394-0.396,0.394-1.037,0-1.432L17.459,16.014z'
      ]
      ,
      [
        'fill',
        '#121313'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_DeleteIconComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'delete-icon',([] as any[]),(null as any),(null as any),(null as any),View_DeleteIconComponent_0,RenderType_DeleteIconComponent)),
    import1.ɵdid(24576,(null as any),0,import2.DeleteIconComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const DeleteIconComponentNgFactory:import1.ComponentFactory<import2.DeleteIconComponent> = import1.ɵccf('delete-icon',import2.DeleteIconComponent,View_DeleteIconComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvaWNvbi9pY29uLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvaWNvbi9pY29uLnRzIiwibmc6Ly8vVXNlcnMvZXlhbGhha2ltL2Rldi9yZXBvcy9uZzItdGFnLWlucHV0L21vZHVsZXMvY29tcG9uZW50cy9pY29uL2ljb24uaHRtbCIsIm5nOi8vL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvaWNvbi9pY29uLnRzLkRlbGV0ZUljb25Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8c3Bhbj5cbiAgICA8c3ZnIGhlaWdodD1cIjE2cHhcIiB2aWV3Qm94PVwiMCAwIDMyIDMyXCIgd2lkdGg9XCIxNnB4XCI+XG4gICAgICAgIDxwYXRoIGQ9XCJNMTcuNDU5LDE2LjAxNGw4LjIzOS04LjE5NGMwLjM5NS0wLjM5MSwwLjM5NS0xLjAyNCwwLTEuNDE0Yy0wLjM5NC0wLjM5MS0xLjAzNC0wLjM5MS0xLjQyOCwwICBsLTguMjMyLDguMTg3TDcuNzMsNi4yODRjLTAuMzk0LTAuMzk1LTEuMDM0LTAuMzk1LTEuNDI4LDBjLTAuMzk0LDAuMzk2LTAuMzk0LDEuMDM3LDAsMS40MzJsOC4zMDIsOC4zMDNsLTguMzMyLDguMjg2ICBjLTAuMzk0LDAuMzkxLTAuMzk0LDEuMDI0LDAsMS40MTRjMC4zOTQsMC4zOTEsMS4wMzQsMC4zOTEsMS40MjgsMGw4LjMyNS04LjI3OWw4LjI3NSw4LjI3NmMwLjM5NCwwLjM5NSwxLjAzNCwwLjM5NSwxLjQyOCwwICBjMC4zOTQtMC4zOTYsMC4zOTQtMS4wMzcsMC0xLjQzMkwxNy40NTksMTYuMDE0elwiXG4gICAgICAgICAgICAgIGZpbGw9XCIjMTIxMzEzXCIgLz5cbiAgICA8L3N2Zz5cbjwvc3Bhbj5cbiIsIjxkZWxldGUtaWNvbj48L2RlbGV0ZS1pY29uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFBTTtJQUNGO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUFvRDtJQUNoRDtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFDdUI7SUFDckI7SUFDSDs7Ozs7O0lDTFA7Z0JBQUE7Ozs7In0=
