/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../modules/components/tag/tag-ripple.component';
const styles_TagRipple:any[] = ['[_nghost-%COMP%] {\n            width: 100%;\n            height: 100%;\n            left: 0;\n            overflow: hidden;\n            position: absolute;\n        }\n        \n        .tag-ripple[_ngcontent-%COMP%] {\n            background: rgba(0, 0, 0, 0.1);\n            top: 50%;\n            left: 50%;\n            height: 100%;\n            transform: translate(-50%, -50%);\n            position: absolute;\n        }'];
export const RenderType_TagRipple:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_TagRipple,
      data: {'animation': [{
        name: 'ink',
        definitions: [
          {
            type: 0,
            name: 'none',
            styles: {
              type: 6,
              styles: {
                width: 0,
                opacity: 0
              }

            }

          }
          ,
          {
            type: 1,
            expr: 'none => clicked',
              animation: [{
                type: 4,
                styles: {
                  type: 5,
                  steps: [
                    {
                      type: 6,
                      styles: {
                        opacity: 1,
                        offset: 0,
                        width: '30%',
                        borderRadius: '100%'
                      }

                    }
                    ,
                    {
                      type: 6,
                      styles: {
                        opacity: 1,
                        offset: 0.5,
                        width: '50%'
                      }

                    }
                    ,
                    {
                      type: 6,
                      styles: {
                        opacity: 0.5,
                        offset: 1,
                        width: '100%',
                        borderRadius: '16px'
                      }

                    }

                  ]

                }
                ,
                timings: 300
              }
            ]
          }

        ]

      }
  ]}
}
);
export function View_TagRipple_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'tag-ripple'
      ]
      ],[[
        24,
        '@ink',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.TagRipple = v.component;
    const currVal_0:any = co.state;
    ck(v,1,0,currVal_0);
  });
}
function View_TagRipple_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'tag-ripple',([] as any[]),(null as any),(null as any),(null as any),View_TagRipple_0,RenderType_TagRipple)),
    import0.ɵdid(24576,(null as any),0,import1.TagRipple,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TagRippleNgFactory:import0.ComponentFactory<import1.TagRipple> = import0.ɵccf('tag-ripple',import1.TagRipple,View_TagRipple_Host_0,{state: 'state'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvdGFnL3RhZy1yaXBwbGUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvdGFnL3RhZy1yaXBwbGUuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvZXlhbGhha2ltL2Rldi9yZXBvcy9uZzItdGFnLWlucHV0L21vZHVsZXMvY29tcG9uZW50cy90YWcvdGFnLXJpcHBsZS5jb21wb25lbnQudHMuVGFnUmlwcGxlLmh0bWwiLCJuZzovLy9Vc2Vycy9leWFsaGFraW0vZGV2L3JlcG9zL25nMi10YWctaW5wdXQvbW9kdWxlcy9jb21wb25lbnRzL3RhZy90YWctcmlwcGxlLmNvbXBvbmVudC50cy5UYWdSaXBwbGVfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGRpdiBjbGFzcz1cInRhZy1yaXBwbGVcIiBbQGlua109XCJzdGF0ZVwiPjwvZGl2PlxuICAgICIsIjx0YWctcmlwcGxlPjwvdGFnLXJpcHBsZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDUTtRQUFBO1FBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUE2Qzs7OztJQUFyQjtJQUF4QixTQUF3QixTQUF4Qjs7Ozs7SUNEUjtnQkFBQTs7OzsifQ==
