/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['[_nghost-%COMP%], [_nghost-%COMP%]    > div[_ngcontent-%COMP%], [_nghost-%COMP%]    > div[_ngcontent-%COMP%]:focus {\n    outline: 0;\n    overflow: hidden;\n    transition: opacity 1s;\n    z-index: 1;\n}\n\n[_nghost-%COMP%] {\n    max-width: 400px;\n}\n\n.blink[_nghost-%COMP%] {\n    -webkit-animation: blink 0.3s normal forwards ease-in-out;\n    animation: blink 0.3s normal forwards ease-in-out;\n}\n@keyframes blink {\n    0% {\n        opacity: 0.3;\n    }\n}\n\n[_nghost-%COMP%]   .disabled[_ngcontent-%COMP%] {\n    cursor: not-allowed;\n}\n\n[_nghost-%COMP%]   [contenteditable=\'true\'][_ngcontent-%COMP%] {\n    outline: 0;\n    user-select: none;\n}\n\n.tag-wrapper[_ngcontent-%COMP%] {\n    flex-direction: row;\n    display: flex;\n}\n\n.tag__text[_ngcontent-%COMP%] {\n    overflow: hidden;\n    text-overflow: ellipsis;\n    white-space: nowrap;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2NvbXBvbmVudHMvdGFnL3RhZy1jb21wb25lbnQuc3R5bGUuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9leWFsaGFraW0vZGV2L3JlcG9zL25nMi10YWctaW5wdXQvbW9kdWxlcy9jb21wb25lbnRzL3RhZy90YWcuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
