/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../modules/index';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from 'ng2-material-dropdown/dist/src/modules/ng2-dropdown.module';
class TagInputModuleInjector extends import0.ɵNgModuleInjector<import1.TagInputModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _ReactiveFormsModule_2:import3.ReactiveFormsModule;
  _FormsModule_3:import3.FormsModule;
  _Ng2DropdownModule_4:import4.Ng2DropdownModule;
  _TagInputModule_5:import1.TagInputModule;
  __NgLocalization_6:import2.NgLocaleLocalization;
  __FormBuilder_7:import3.FormBuilder;
  __ɵi_8:import3.ɵi;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_6():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == null)) { (this.__NgLocalization_6 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_6;
  }
  get _FormBuilder_7():import3.FormBuilder {
    if ((this.__FormBuilder_7 == null)) { (this.__FormBuilder_7 = new import3.FormBuilder()); }
    return this.__FormBuilder_7;
  }
  get _ɵi_8():import3.ɵi {
    if ((this.__ɵi_8 == null)) { (this.__ɵi_8 = new import3.ɵi()); }
    return this.__ɵi_8;
  }
  createInternal():import1.TagInputModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._ReactiveFormsModule_2 = new import3.ReactiveFormsModule();
    this._FormsModule_3 = new import3.FormsModule();
    this._Ng2DropdownModule_4 = new import4.Ng2DropdownModule();
    this._TagInputModule_5 = new import1.TagInputModule();
    return this._TagInputModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_2; }
    if ((token === import3.FormsModule)) { return this._FormsModule_3; }
    if ((token === import4.Ng2DropdownModule)) { return this._Ng2DropdownModule_4; }
    if ((token === import1.TagInputModule)) { return this._TagInputModule_5; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_7; }
    if ((token === import3.ɵi)) { return this._ɵi_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TagInputModuleNgFactory:import0.NgModuleFactory<import1.TagInputModule> = new import0.NgModuleFactory<any>(TagInputModuleInjector,import1.TagInputModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2luZGV4Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2V5YWxoYWtpbS9kZXYvcmVwb3MvbmcyLXRhZy1pbnB1dC9tb2R1bGVzL2luZGV4LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
